// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIPBinding(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Disconnect():Promise<string>;

export function GetHotspotServers():Promise<Array<string>>;

export function GetIPBindings():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function RemoveIPBinding(arg1:string):Promise<string>;
