// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIPBinding(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddIPBinding'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetHotspotServers() {
  return window['go']['main']['App']['GetHotspotServers']();
}

export function GetIPBindings() {
  return window['go']['main']['App']['GetIPBindings']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function RemoveIPBinding(arg1) {
  return window['go']['main']['App']['RemoveIPBinding'](arg1);
}
